name: Monkey CI - PRs

env:
  PNPM_VERSION: "10.33.0"
  NODE_VERSION: "24.15.0"
  RECAPTCHA_SITE_KEY: "6Lc-V8McAAAAAJ7s6LGNe7MBZnRiwbsbiWts87aj"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, ready_for_review]

concurrency:
  group: group-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  pre-ci:
    name: pre-ci
    runs-on: ubuntu-latest
    outputs:
      should-build-be: ${{ steps.export-changes.outputs.should-build-be }}
      should-build-fe: ${{ steps.export-changes.outputs.should-build-fe }}
      should-build-pkg: ${{ steps.export-changes.outputs.should-build-pkg }}
      assets-or-styles: ${{ steps.export-changes.outputs.assets-or-styles }}

    steps:
      - name: Full checkout
        uses: actions/checkout@v5

      - name: Detect changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            assets-or-styles:
              - 'frontend/static/**/*'
              - '**/*.{scss,css}'
            be-src:
              - 'backend/**/*.{ts,js,json,lua,css,html}'
              - 'backend/package.json'
            fe-src:
              - 'frontend/**/*.{ts,scss,html}'
              - 'frontend/package.json'
            pkg-src:
              - 'packages/**/*'

      - name: Export changes
        id: export-changes
        run: |
          echo "should-build-pkg=${{ steps.filter.outputs.pkg-src }}" >> $GITHUB_OUTPUT
          echo "should-build-be=${{ steps.filter.outputs.be-src }}" >> $GITHUB_OUTPUT
          echo "should-build-fe=${{ steps.filter.outputs.fe-src }}" >> $GITHUB_OUTPUT
          echo "assets-or-styles=${{ steps.filter.outputs.assets-or-styles }}" >> $GITHUB_OUTPUT

  prime-cache:
    name: prime-cache
    runs-on: ubuntu-latest
    needs: [pre-ci]
    if: needs.pre-ci.outputs.should-build-be == 'true' || needs.pre-ci.outputs.should-build-fe == 'true' || needs.pre-ci.outputs.should-build-pkg == 'true' || needs.pre-ci.outputs.assets-or-styles == 'true' || contains(github.event.pull_request.labels.*.name, 'force-full-ci') || contains(github.event.pull_request.labels.*.name, 'full-check-ci')
    steps:
      - name: Full checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: ${{ env.PNPM_VERSION }}
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: CI=true pnpm install --frozen-lockfile --no-optional

  full-check:
    name: full-check
    needs: [prime-cache]
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'full-check-ci')
    steps:
      - name: Full checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: ${{ env.PNPM_VERSION }}
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: CI=true pnpm install --frozen-lockfile --no-optional

      - name: Run full check
        run: pnpm full-check

  ci-be:
    name: ci-be
    needs: [pre-ci, prime-cache]
    runs-on: ubuntu-latest
    if: needs.pre-ci.outputs.should-build-be == 'true' || needs.pre-ci.outputs.should-build-pkg == 'true' || contains(github.event.pull_request.labels.*.name, 'force-full-ci')
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            backend
            packages

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: ${{ env.PNPM_VERSION }}
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: CI=true pnpm install --frozen-lockfile --no-optional

      - name: Check lint
        run: pnpm lint-fast-be && pnpm lint-be

      - name: Build
        run: pnpm build-be

      - name: Test
        run: pnpm test-be

  ci-fe:
    name: ci-fe
    needs: [pre-ci, prime-cache]
    runs-on: ubuntu-latest
    if: needs.pre-ci.outputs.should-build-fe == 'true' || needs.pre-ci.outputs.should-build-pkg == 'true' || contains(github.event.pull_request.labels.*.name, 'force-full-ci')
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            frontend
            packages

      - name: Create stub firebase config
        working-directory: ./frontend/src/ts/constants
        run: mv ./firebase-config-example.ts ./firebase-config.ts && cp ./firebase-config.ts ./firebase-config-live.ts

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: ${{ env.PNPM_VERSION }}
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: CI=true pnpm install --frozen-lockfile --no-optional

      - name: Check lint
        run: pnpm lint-fast-fe && pnpm lint-fe

      - name: Build
        run: pnpm build-fe

      - name: Test
        run: pnpm test-fe

  ci-assets:
    name: ci-assets
    needs: [pre-ci, prime-cache]
    runs-on: ubuntu-latest
    if: needs.pre-ci.outputs.assets-or-styles == 'true' || contains(github.event.pull_request.labels.*.name, 'force-full-ci')
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            frontend
            packages

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            styles:
              - '**/*.{scss,css}'
            json:
              - 'frontend/static/**/*.json'
            languages:
              - 'frontend/static/languages/**'
            quotes:
              - 'frontend/static/quotes/**'
            others:
              - 'frontend/static/layouts/**'
              - 'frontend/static/themes/**'
              - 'frontend/static/webfonts/**'
              - 'frontend/static/challenges/**'

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: ${{ env.PNPM_VERSION }}
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: CI=true pnpm install --frozen-lockfile --no-optional

      - name: Lint styles
        if: steps.filter.outputs.styles == 'true' || contains(github.event.pull_request.labels.*.name, 'force-full-ci')
        run: pnpm lint-styles

      - name: Lint JSON
        if: steps.filter.outputs.json == 'true' || contains(github.event.pull_request.labels.*.name, 'force-full-ci')
        run: pnpm lint-json-assets

      - name: Validate language assets
        if: steps.filter.outputs.languages == 'true' || contains(github.event.pull_request.labels.*.name, 'force-full-ci')
        run: pnpm check-assets-languages

      - name: Validate quote assets
        if: steps.filter.outputs.quotes == 'true' || contains(github.event.pull_request.labels.*.name, 'force-full-ci')
        run: pnpm check-assets-quotes

      - name: Validate other assets
        if: steps.filter.outputs.others == 'true' || contains(github.event.pull_request.labels.*.name, 'force-full-ci')
        run: pnpm check-assets-others

  ci-pkg:
    name: ci-pkg
    needs: [pre-ci, prime-cache]
    runs-on: ubuntu-latest
    if: needs.pre-ci.outputs.should-build-pkg == 'true' || contains(github.event.pull_request.labels.*.name, 'force-full-ci')
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            packages

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: ${{ env.PNPM_VERSION }}
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: CI=true pnpm install --frozen-lockfile --no-optional

      - name: Check lint
        run: pnpm lint-fast-pkg && pnpm lint-pkg

      - name: Build
        run: pnpm build-pkg

      - name: Test
        run: pnpm test-pkg
